# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cc2b60527dfa35bb30e37c35be8c8068a8cf3f9b2dd8145a36fb8784e82ed82a9644e4e3db438440870cd18448642fac4f71e2249b49965c0315fc1ffdbf26f

test:
  secret_key_base: aa58d53f3d28a3534ccb06b56c6d97e4cceb28ae544d157d950ef90d6639269b72eccd79301b1e1116cb53e032d594a6adc62533e2bed46c5f85c923af16e2e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
